---
title: Guillermoermel.Github.Io
timezone: UTC
collections:
  blah:
    title: Blah
    output: true
  bleh:
    title: Bleh
    output: true
  people:
    title: People
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
theme: jekyll-theme-minimal
name: Hank Quinlan, Horrible Cop
markdown: kramdown
