---
title: Guillermoermel.Github.Io
timezone: UTC
collections:
  people:
    title: People
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
theme: jekyll-theme-minimal
name: Hank Quinlan, Horrible Cop
markdown: kramdown
